using TestRig.Core;

namespace TestRig.BuildTool;

/// <summary>
/// Emits the generated source-hash constant for TestRig.Cli.
/// </summary>
/// <remarks>
/// Usage: <c>TestRig.BuildTool emit-source-hash &lt;srcRoot&gt; &lt;outFile&gt;</c>
///
/// Deliberately calls <see cref="SourceHash.Compute"/> rather than reimplementing it,
/// so the value baked into the binary and the value the binary recomputes at startup
/// come from one piece of code.
/// </remarks>
internal static class Program
{
    private static int Main(string[] args)
    {
        if (args.Length != 3 || args[0] != "emit-source-hash")
        {
            Console.Error.WriteLine("usage: TestRig.BuildTool emit-source-hash <srcRoot> <outFile>");
            return 2;
        }

        var srcRoot = args[1];
        var outFile = args[2];

        var result = SourceHash.Compute(srcRoot);

        var content = $$"""
            // <auto-generated/> Emitted by TestRig.BuildTool during the build.
            // Do not edit and do not hand-write a value. See TestRig/src/CLAUDE.md.
            namespace TestRig.Cli;

            internal static partial class BuildStamp
            {
                /// <summary>Digest of TestRig/src at the moment this binary was compiled.</summary>
                public const string SourceHash = "{{result.Hash}}";

                /// <summary>Number of source files the digest covers.</summary>
                public const int SourceFileCount = {{result.FileCount}};
            }

            """;

        var dir = Path.GetDirectoryName(outFile);
        if (!string.IsNullOrEmpty(dir)) Directory.CreateDirectory(dir);

        // Only rewrite when the value actually changed, so an unchanged tree does not
        // force a recompile on every build.
        if (!File.Exists(outFile) || File.ReadAllText(outFile) != content)
        {
            File.WriteAllText(outFile, content, new System.Text.UTF8Encoding(false));
        }

        Console.WriteLine($"source hash {result.Hash} over {result.FileCount} files");
        return 0;
    }
}
